/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/places`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/lib/better-auth`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/app/api/auth/[...all]/route`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/lib/auth-client`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/app/login/magic-link/page`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/lib/api-errors`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/lib/parse-api-error`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/places`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/lib/better-auth`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/app/api/auth/[...all]/route`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/lib/auth-client`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/app/login/magic-link/page`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/lib/api-errors`; params?: Router.UnknownOutputParams; } | { pathname: `/../../web/lib/parse-api-error`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/chat${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/places${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `/../../web/lib/better-auth${`?${string}` | `#${string}` | ''}` | `/../../web/app/api/auth/[...all]/route${`?${string}` | `#${string}` | ''}` | `/../../web/lib/auth-client${`?${string}` | `#${string}` | ''}` | `/../../web/app/login/magic-link/page${`?${string}` | `#${string}` | ''}` | `/../../web/lib/api-errors${`?${string}` | `#${string}` | ''}` | `/../../web/lib/parse-api-error${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/chat`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/places`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/lib/better-auth`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/app/api/auth/[...all]/route`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/lib/auth-client`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/app/login/magic-link/page`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/lib/api-errors`; params?: Router.UnknownInputParams; } | { pathname: `/../../web/lib/parse-api-error`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
